services:
  nginx-web:
    image: nginx:latest
    ports:
    - "88:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  app:
    build:
      dockerfile: ./php/Dockerfile
      target: ${BUILD_TARGET:-app}
    volumes:
      - ./app:/var/www/html
      - ./php/conf.d/xdebug.ini:/user/local/etc/php/conf.d/xdebug.ini:ro
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      REDIS_HOST: cache
      REDIS_PORT: ${REDIS_PORT}
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      - host.docker.internal:host-gateway
  mysqldb:
    image: mysql:8.0
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: docker-php
  cache:
    image: redis:latest

volumes:
  mysqldata: